### successful POST req of blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Magic",
  "author": "Parry Hotter",
  "url": "https://www.magickedawayblog.com/",
  "likes": 5
}

### unsuccessful POST req, unknown endpoint
POST http://localhost:3003/api/blog
Content-Type: application/json

{
  "title": "The Void",
  "author": "unknown",
  "url": "https://www.nothingness.org",
  "likes": 0
}
